import {
  Activity,
  Bitcoin,
  Briefcase,
  Camera,
  Cloud,
  Cpu,
  Database,
  Dumbbell,
  FileText,
  Folder,
  Globe,
  Layers,
  Lock,
  Music,
  PenTool,
  Play,
  Smartphone,
  Sparkles,
  Sun,
  Utensils,
} from 'lucide-react';
import type { CategoryConfig, Project, ProjectCategory } from './types';

export const demoImages = {
  app1: 'https://images.unsplash.com/photo-1512941937669-90a1b5bbb695?w=800&q=80',
  app2: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800&q=80',
  app3: 'https://images.unsplash.com/photo-1555421689-d68471e189f2?w=800&q=80',
  code: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
  mock1: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&q=80',
  mock2: 'https://images.unsplash.com/photo-1616469829581-73993eb86b02?w=800&q=80',
  videoPlaceholder: 'https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=800&q=80',
};

export const projects: Project[] = [
  {
    id: 'proj-1',
    title: 'SnapDaily',
    category: 'app',
    year: '2024',
    role: 'Solo Dev',
    tagline: 'Capture life, one second at a time.',
    description: '「継続する楽しさ」をテーマにした動画日記アプリ。',
    longDescription:
      'SnapDailyは、日常の何気ない瞬間を1秒の動画として記録し、それをつなぎ合わせて人生のハイライトムービーを作成するアプリです。従来の重たい日記アプリとは異なり、「撮るだけ」の軽快さを追求しました。',
    features: [
      '1秒動画の超高速撮影＆保存',
      'カレンダービューでの視覚的な思い出管理',
      'AIによる自動ハイライト生成機能',
      'iCloud同期によるデバイス間連携',
      'プライバシー重視のローカルファースト設計',
    ],
    challenges:
      '大量の動画ファイルを扱いながらも、スクロールのカクつきをゼロにするために、AVAssetの非同期読み込みとキャッシング戦略を徹底的にチューニングしました。また、カスタムトランジションを自作し、画面遷移そのものが楽しくなるような演出を施しています。',
    techStack: ['SwiftUI', 'AVFoundation', 'CoreData', 'CloudKit'],
    color: 'from-cyan-400 via-blue-500 to-indigo-500',
    accent: 'text-cyan-600 bg-cyan-50',
    icon: Smartphone,
    gallery: [demoImages.app1, demoImages.mock1, demoImages.app2],
    videoUrl: 'https://example.com/demo.mp4',
    appStoreUrl: 'https://apple.com',
  },
  {
    id: 'proj-1b',
    title: 'FocusZen',
    category: 'app',
    year: '2024',
    role: 'Solo Dev',
    tagline: 'Meditate with AI.',
    description: 'AIが生成する環境音で集中力を高める瞑想アプリ。',
    longDescription: 'ユーザーの心拍数（Watch連携）に合わせてリアルタイムに環境音を生成・変化させるリラクゼーションアプリ。',
    features: ['リアルタイム音生成', 'Apple Watch連携', 'ヘルスケア統合'],
    challenges: 'Core Audioを用いた低遅延なオーディオ処理と、オンデバイスAIモデルの省電力化の両立。',
    techStack: ['Swift', 'CoreAudio', 'HealthKit'],
    color: 'from-teal-400 via-emerald-500 to-green-500',
    accent: 'text-emerald-600 bg-emerald-50',
    icon: Music,
    gallery: [demoImages.app1],
  },
  {
    id: 'proj-1c',
    title: 'RetroCam',
    category: 'app',
    year: '2023',
    role: 'Solo Dev',
    tagline: '80s filters for modern life.',
    description: '80年代のフィルム質感を再現するカメラアプリ。',
    longDescription: 'Metalシェーダーを駆使して、リアルタイムにフィルムノイズや色収差を適用する高機能カメラ。',
    features: ['カスタムMetalシェーダー', 'RAW撮影', 'マニュアルフォーカス'],
    challenges: '4Kビデオ録画時のリアルタイムエフェクト適用におけるGPU負荷の最適化。',
    techStack: ['Swift', 'Metal', 'AVFoundation'],
    color: 'from-pink-400 via-rose-500 to-red-500',
    accent: 'text-rose-600 bg-rose-50',
    icon: Camera,
    gallery: [demoImages.app2],
  },
  {
    id: 'proj-1d',
    title: 'PixelArt Maker',
    category: 'app',
    year: '2023',
    role: 'Creator',
    tagline: 'Draw pixels anywhere.',
    description: 'スマホで手軽にドット絵が描けるクリエイティブツール。',
    longDescription:
      'レイヤー機能、アニメーション作成機能、カスタムパレット作成機能を備えた本格的なドット絵エディタ。Apple Pencilにも対応。',
    features: ['レイヤー編集', 'GIF書き出し', 'iCloud同期'],
    challenges: 'キャンバスの拡大縮小時の描画パフォーマンスと、タッチ精度の調整。',
    techStack: ['SwiftUI', 'PencilKit', 'CoreGraphics'],
    color: 'from-indigo-400 via-purple-500 to-pink-500',
    accent: 'text-purple-600 bg-purple-50',
    icon: PenTool,
    gallery: [demoImages.mock2],
  },
  {
    id: 'proj-1e',
    title: 'WeatherNow',
    category: 'app',
    year: '2023',
    role: 'Dev',
    tagline: 'Beautiful weather forecasts.',
    description: '美しいグラデーションで天気を表現する予報アプリ。',
    longDescription: '天気APIから取得したデータに基づき、空の色をシミュレートして背景グラデーションを動的に生成します。',
    features: ['動的グラデーション', 'ウィジェット対応', '雨雲レーダー'],
    challenges: 'OpenWeatherMap APIとの効率的な通信と、キャッシュによるレスポンス向上。',
    techStack: ['Swift', 'WidgetKit', 'WeatherKit'],
    color: 'from-sky-400 via-blue-500 to-blue-600',
    accent: 'text-blue-600 bg-blue-50',
    icon: Sun,
    gallery: [demoImages.app3],
  },
  {
    id: 'proj-1f',
    title: 'HabitLoop',
    category: 'app',
    year: '2022',
    role: 'Solo Dev',
    tagline: 'Build better habits.',
    description: 'ゲーミフィケーション要素を取り入れた習慣化支援アプリ。',
    longDescription: '習慣の継続日数に応じてキャラクターが成長するRPG要素を取り入れ、ユーザーのモチベーション維持をサポート。',
    features: ['習慣トラッキング', 'キャラクター育成', '通知リマインダー'],
    challenges: 'ローカル通知の複雑なスケジュール管理と、Core Dataのマイグレーション処理。',
    techStack: ['Swift', 'UserNotifications', 'CoreData'],
    color: 'from-amber-400 via-orange-500 to-red-500',
    accent: 'text-orange-600 bg-orange-50',
    icon: Activity,
    gallery: [demoImages.app1],
  },
  {
    id: 'proj-1g',
    title: 'CryptoTracker',
    category: 'app',
    year: '2022',
    role: 'Dev',
    tagline: 'Crypto market at glance.',
    description: '暗号資産のリアルタイム価格とポートフォリオ管理。',
    longDescription: 'WebSocketを使用してリアルタイムに価格変動をチャート描画。複数の取引所APIに対応。',
    features: ['リアルタイムチャート', 'ポートフォリオ分析', '価格アラート'],
    challenges: '大量のWebSocketメッセージ処理によるメモリリークの防止と、チャート描画の軽量化。',
    techStack: ['Swift', 'SwiftUI Charts', 'WebSocket'],
    color: 'from-yellow-400 via-yellow-500 to-orange-500',
    accent: 'text-yellow-600 bg-yellow-50',
    icon: Bitcoin,
    gallery: [demoImages.mock1],
  },
  {
    id: 'proj-1h',
    title: 'RecipeBook',
    category: 'app',
    year: '2022',
    role: 'Designer',
    tagline: 'Cook with confidence.',
    description: 'ステップバイステップで料理をサポートするレシピアプリ。',
    longDescription: '手が汚れていても操作できるよう、音声コマンドによるページめくり機能を搭載。',
    features: ['音声操作', '買い物リスト', '栄養素計算'],
    challenges: 'Speech Frameworkを用いた音声認識の精度向上と、誤検知の抑制。',
    techStack: ['Swift', 'Speech', 'CoreML'],
    color: 'from-green-400 via-emerald-500 to-teal-500',
    accent: 'text-green-600 bg-green-50',
    icon: Utensils,
    gallery: [demoImages.app2],
  },
  {
    id: 'proj-1i',
    title: 'GymLog',
    category: 'app',
    year: '2021',
    role: 'Solo Dev',
    tagline: 'Track your gains.',
    description: '筋トレの記録と分析に特化したワークアウトログ。',
    longDescription: '1RM（最大挙上重量）の推移グラフや、部位別のトレーニングボリュームを可視化。',
    features: ['ワークアウト記録', '1RM計算', 'グラフ分析'],
    challenges: '複雑なクエリを含むCore Dataのパフォーマンスチューニング。',
    techStack: ['Swift', 'CoreData', 'Charts'],
    color: 'from-red-500 via-red-600 to-rose-600',
    accent: 'text-red-600 bg-red-50',
    icon: Dumbbell,
    gallery: [demoImages.mock2],
  },
  {
    id: 'proj-1j',
    title: 'StarGazer',
    category: 'app',
    year: '2021',
    role: 'Dev',
    tagline: 'Map of the stars.',
    description: 'ジャイロセンサーを使ったAR星座早見盤。',
    longDescription: 'デバイスを空にかざすだけで、その方向にある星座や惑星の名前を表示。',
    features: ['AR星座表示', '惑星トラッキング', '月齢カレンダー'],
    challenges: 'Core Motionセンサーの値をスムーズに補間し、AR表示のブレを軽減する処理。',
    techStack: ['Swift', 'CoreMotion', 'SceneKit'],
    color: 'from-indigo-600 via-violet-600 to-purple-600',
    accent: 'text-indigo-600 bg-indigo-50',
    icon: Sparkles,
    gallery: [demoImages.app3],
  },
  {
    id: 'proj-2',
    title: 'TaskFlow Pro',
    category: 'client',
    year: '2023',
    role: 'Lead Eng',
    tagline: 'Productivity for iPad.',
    description: 'iPad対応を含むユニバーサルタスク管理アプリ。',
    longDescription:
      'プロフェッショナル向けのタスク管理ツールとして、iPadの大画面を最大限に活かした3カラムレイアウトを採用。ドラッグ&ドロップによる直感的なタスク整理と、複雑なプロジェクト管理を両立させました。',
    features: [
      'iPadOSに最適化されたマルチカラムUI',
      'PencilKitを活用した手書きメモ機能',
      'ウィジェット対応',
      'Siriショートカット連携',
      'チーム共有機能',
    ],
    challenges:
      'Core DataとCloudKitの同期において、オフライン時のデータ整合性を保つためのコンフリクト解決ロジックの実装に苦労しました。また、iPadのマルチタスク機能（Split View, Slide Over）に完全対応させるため、レスポンシブなレイアウト設計を行っています。',
    techStack: ['UIKit', 'CoreData', 'PencilKit', 'CloudKit'],
    color: 'from-violet-400 via-purple-500 to-fuchsia-500',
    accent: 'text-purple-600 bg-purple-50',
    icon: Layers,
    gallery: [demoImages.app3, demoImages.mock2],
  },
  {
    id: 'proj-2b',
    title: 'BankSecure',
    category: 'client',
    year: '2023',
    role: 'Senior Eng',
    tagline: 'Next-gen Banking App.',
    description: '大手地方銀行の次世代バンキングアプリリニューアル。',
    longDescription: '生体認証を活用したセキュアかつスムーズなログイン体験と、モダンなUI/UXへの刷新を担当。',
    features: ['FaceID/TouchID統合', '振込フローの簡略化', '家計簿機能'],
    challenges: '堅牢なセキュリティ要件を満たしつつ、React Nativeの一部導入による開発効率化を実現。',
    techStack: ['Swift', 'Objective-C', 'Security framework'],
    color: 'from-slate-600 via-slate-700 to-slate-800',
    accent: 'text-slate-600 bg-slate-50',
    icon: Lock,
    gallery: [demoImages.mock1],
  },
  {
    id: 'proj-2c',
    title: 'EduMate',
    category: 'client',
    year: '2022',
    role: 'iOS Eng',
    tagline: 'Learning management system.',
    description: '教育機関向けLMSのiOSクライアント開発。',
    longDescription: '数千人の学生が同時アクセスしても安定するチャット機能と、オフライン教材閲覧機能を実装。',
    features: ['リアルタイムチャット', 'オフラインモード', '課題提出'],
    challenges: '大量のPDF/動画教材のキャッシュ管理とバックグラウンドダウンロードの制御。',
    techStack: ['Swift', 'Realm', 'Firebase'],
    color: 'from-orange-400 via-amber-500 to-yellow-500',
    accent: 'text-amber-600 bg-amber-50',
    icon: Database,
    gallery: [demoImages.app3],
  },
  {
    id: 'proj-2d',
    title: 'CityGuide AR',
    category: 'client',
    year: '2022',
    role: 'AR Dev',
    tagline: 'Explore the city.',
    description: '観光客向けのARナビゲーションアプリ。',
    longDescription: 'GPSとVPS（Visual Positioning System）を組み合わせた高精度なAR道案内。',
    features: ['ARナビゲーション', '多言語対応', 'クーポン配信'],
    challenges: '屋外環境でのAR表示の安定性向上とバッテリー消費の抑制。',
    techStack: ['Unity', 'ARFoundation', 'Mapbox'],
    color: 'from-cyan-400 via-sky-500 to-blue-500',
    accent: 'text-sky-600 bg-sky-50',
    icon: Globe,
    gallery: [demoImages.app2],
  },
  {
    id: 'proj-3',
    title: 'EcoScanner',
    category: 'client',
    year: '2023',
    role: 'ML Engineer',
    tagline: 'AI that sees the future.',
    description: 'デバイスオンデバイスでプラスチックの種類を判別するARスキャナー。',
    longDescription:
      '環境保護を目的とした、プラスチックのリサイクル区分を即座に判定するARアプリです。カメラをかざすだけで、素材（PET, PS, PPなど）をAIが識別し、正しい廃棄方法をARでオーバーレイ表示します。',
    features: [
      'リアルタイム物体検出',
      'ARによる情報オーバーレイ',
      'オフライン動作可能な軽量MLモデル',
      'リサイクルログの可視化',
    ],
    challenges:
      'Create MLを使用して独自データセットから学習モデルを作成しましたが、透明なプラスチックの識別精度を上げるのが最大の課題でした。照明条件による精度のばらつきを抑えるため、画像前処理パイプラインを工夫しています。',
    techStack: ['CoreML', 'ARKit', 'Vision', 'SwiftUI'],
    color: 'from-emerald-400 via-teal-500 to-cyan-500',
    accent: 'text-teal-600 bg-teal-50',
    icon: Cpu,
    gallery: [demoImages.code, demoImages.app2],
  },
  {
    id: 'proj-4',
    title: 'Portfolio v2',
    category: 'web',
    year: '2025',
    role: 'Design & Dev',
    tagline: 'My digital playground.',
    description: 'iOSエンジニアとしてのアイデンティティをWebで表現。',
    longDescription:
      'Web技術（React, Tailwind CSS）を用いて、ネイティブアプリのような「触り心地」をWeb上で再現することを目指したポートフォリオサイトです。流体的なアニメーションと、細部まで作り込まれたマイクロインタラクションが特徴です。',
    features: ['物理演算風のインタラクション', 'グラスモーフィズムデザイン', '完全レスポンシブ対応', 'ダークモード対応（予定）'],
    challenges:
      'Framer Motionなどのライブラリに頼らず、React標準の機能とCSSのみで複雑なアニメーションを実現することで、パフォーマンスとバンドルサイズの最適化を図りました。',
    techStack: ['Next.js', 'React', 'Tailwind CSS'],
    color: 'from-amber-400 via-orange-500 to-red-500',
    accent: 'text-orange-600 bg-orange-50',
    icon: Globe,
    gallery: [demoImages.code, demoImages.app1],
    webUrl: 'https://fundriven.dev',
    githubUrl: 'https://github.com/fundriven',
  },
  {
    id: 'proj-4b',
    title: 'TechBlog',
    category: 'web',
    year: '2024',
    role: 'Dev',
    tagline: 'Engineering insights.',
    description: '技術的知見を共有するためのMDXベースのブログ。',
    longDescription: 'SSGによる高速なページロードと、シンタックスハイライトにこだわった技術ブログ。',
    features: ['MDXサポート', 'ダークモード', 'OGP自動生成'],
    challenges: 'Next.jsのApp Router移行とServer Componentsの活用。',
    techStack: ['Next.js', 'Vercel', 'Tailwind'],
    color: 'from-indigo-400 via-blue-500 to-sky-500',
    accent: 'text-blue-600 bg-blue-50',
    icon: FileText,
    gallery: [demoImages.code],
  },
];

export const projectCategoryIds: readonly ProjectCategory[] = ['app', 'web', 'client'];

export const categories: CategoryConfig[] = [
  { id: 'app', label: '自社アプリ', subLabel: 'Personal Apps', icon: Smartphone },
  { id: 'web', label: '自社サイト', subLabel: 'Official Site', icon: Globe },
  { id: 'client', label: '受託開発', subLabel: 'Client Works', icon: Briefcase },
];

export const projectCategoryLabel: Record<Project['category'], string> = {
  app: 'Personal App',
  web: 'Official Site',
  client: 'Client Work',
};

export const projectLookup = projects.reduce<Record<string, Project>>((acc, project) => {
  acc[project.id] = project;
  return acc;
}, {});
