import { StyleSheet } from 'react-native';
import { COLORS, radius, spacing } from '../../app/designTokens';
import { commonShadow, menuCardShadow } from './shared';

export const menuStyles = StyleSheet.create({
  menuShadow: {
    ...commonShadow,
  },
  menuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  menuPanel: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 320,
    maxWidth: '92%',
    backgroundColor: 'transparent',
    overflow: 'hidden',
    borderTopRightRadius: 28,
    borderBottomRightRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
    ...commonShadow,
  },
  menuPanelGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  menuPanelGlowTop: {
    position: 'absolute',
    top: -80,
    left: -60,
    width: 240,
    height: 240,
    borderRadius: 120,
    opacity: 0.9,
  },
  menuPanelGlowBottom: {
    position: 'absolute',
    bottom: -100,
    right: -80,
    width: 260,
    height: 260,
    borderRadius: 130,
    opacity: 0.85,
  },
  menuPanelEdgeFade: {
    position: 'absolute',
    right: -12,
    top: 0,
    bottom: 0,
    width: 32,
    opacity: 0.9,
  },
  menuPanelContent: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
  },
  menuSurface: {
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderRadius: radius.xl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
    ...menuCardShadow,
  },
  menuHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    paddingTop: spacing.md,
    paddingHorizontal: spacing.sm,
    paddingBottom: spacing.sm,
  },
  menuCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.9)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(0,0,0,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  menuUserCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.xl,
    gap: spacing.sm,
    minHeight: 56,
  },
  menuAccountRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  menuUserCardPressable: {
    flex: 1,
    borderRadius: radius.xl,
    overflow: 'hidden',
  },
  menuAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(0,122,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.sm,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(0,0,0,0.05)',
  },
  menuAvatarText: {
    fontSize: 18,
    fontWeight: '700',
    color: COLORS.primary,
  },
  menuUserName: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.textMain,
    marginBottom: 2,
  },
  menuUserRole: {
    fontSize: 12,
    color: COLORS.textSub,
    fontWeight: '500',
  },
  menuAccountMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginTop: 2,
  },
  menuAccountTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 0,
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    backgroundColor: 'rgba(0,122,255,0.08)',
  },
  menuAccountTagText: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.primary,
  },
  menuAccountRoleBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: radius.md,
    backgroundColor: 'rgba(0,122,255,0.12)',
  },
  menuAccountRoleText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.textMain,
  },
  menuScroll: {
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl,
    paddingHorizontal: spacing.xs,
    gap: spacing.md,
  },
  menuScrollView: {
    flex: 1,
  },
  menuSection: {
    marginBottom: 0,
  },
  menuSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: spacing.xs,
    paddingHorizontal: spacing.sm,
  },
  menuSectionTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: COLORS.textSub,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  menuOrgCard: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
    gap: spacing.xs,
    overflow: 'hidden',
  },
  menuCardBg: {
    ...StyleSheet.absoluteFillObject,
    zIndex: -1,
  },
  menuOrgText: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textMain,
  },
  menuAccordionCard: {
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderRadius: radius.xl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
    gap: spacing.xs,
  },
  menuAccordionSurface: {
    overflow: 'hidden',
  },
  menuAccordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
  },
  menuAccordionHeaderPressed: {
    opacity: 0.85,
  },
  menuAccordionIconWrapper: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(0,122,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
  },
  menuAccordionIconWrapperSuccess: {
    backgroundColor: 'rgba(52,199,89,0.12)',
  },
  menuAccordionIconWrapperNeutral: {
    backgroundColor: 'rgba(0,0,0,0.05)',
  },
  menuAccordionLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: COLORS.textSub,
    marginBottom: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  menuAccordionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.textMain,
  },
  menuAccordionContentWrapper: {
    overflow: 'hidden',
  },
  menuAccordionContent: {
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.xs,
  },
  menuListRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.xs,
    backgroundColor: 'rgba(255,255,255,0.5)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
  },
  menuListRowActive: {
    backgroundColor: 'rgba(0,122,255,0.08)',
    borderColor: 'rgba(0,122,255,0.35)',
  },
  menuListLabel: {
    fontSize: 14,
    color: COLORS.textSub,
    fontWeight: '500',
  },
  menuListLabelActive: {
    color: COLORS.primary,
    fontWeight: '600',
  },
  menuDivider: {
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.7)',
    marginVertical: spacing.xs,
    marginHorizontal: -spacing.lg,
  },
  menuQuickActionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    backgroundColor: 'rgba(255,255,255,0.74)',
    borderRadius: radius.lg,
    marginBottom: spacing.xs,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.65)',
  },
  menuQuickActionPressable: {
    borderRadius: radius.lg,
  },
  menuQuickActionPressablePressed: {
    opacity: 0.85,
    transform: [{ scale: 0.98 }],
  },
  menuQuickActionIcon: {
    width: 40,
    height: 40,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.md,
  },
  menuQuickActionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.textMain,
    marginBottom: 2,
  },
  menuQuickActionSub: {
    fontSize: 12,
    color: COLORS.textSub,
  },
  menuSubItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    marginBottom: spacing.xs,
    backgroundColor: 'rgba(255,255,255,0.58)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.7)',
  },
  menuSubItemIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.sm,
  },
  menuSubItemLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.textMain,
  },
  menuLogoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    backgroundColor: 'rgba(255,59,48,0.06)',
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: 'rgba(255,59,48,0.15)',
    marginBottom: spacing.sm,
    backgroundColor: 'rgba(255,255,255,0.6)',
  },
  menuLogoutLabel: {
    fontSize: 14,
    color: COLORS.danger,
    fontWeight: '700',
  },
  menuVersionText: {
    fontSize: 11,
    color: COLORS.textSub,
    textAlign: 'center',
    marginTop: spacing.xs,
  },
});

